"""Neural Evolutionary Algorithm baseline (Holliday et al., 2024).

Wraps pre-computed EA/NEA routes for evaluation in AlphaTransit's simulator.
Routes are generated by Holliday et al.'s transit_learning code and stored
as pickle files in output_routes/.

Usage:
    python main.py --mode baseline --baseline_type neural_evolutionary --alpha 0.3
    python main.py --mode baseline --baseline_type evolutionary --alpha 0.3
"""

import os
import csv
import pickle
import numpy as np

BASELINE_DIR = os.path.dirname(os.path.abspath(__file__))

ROUTE_FILES = {
    "nea": os.path.join(BASELINE_DIR, "output_routes",
                        "neural_bco_bloomington_nea_pretrained_routes.pkl"),
    "ea": os.path.join(BASELINE_DIR, "output_routes",
                       "bco_bloomington_ea_nikolic_routes.pkl"),
    "lc100": os.path.join(BASELINE_DIR, "output_routes",
                          "nn_construction_bloomington_lc100_seed0_routes.pkl"),
}


def _load_node_mapping():
    """Load Mumford 0-indexed -> AlphaTransit node name mapping."""
    mapping_path = os.path.join(BASELINE_DIR, "datasets", "bloomington",
                                "node_mapping.csv")
    idx_to_name = {}
    with open(mapping_path, "r") as f:
        reader = csv.DictReader(f)
        for row in reader:
            idx = int(row["mumford_idx"])
            name = row["original_name"]
            idx_to_name[idx] = name
    return idx_to_name


def _load_routes(pkl_path):
    """Load routes from Holliday's pickle format -> List[List[str]]."""
    try:
        import torch
        with open(pkl_path, "rb") as f:
            routes_data = pickle.load(f)
        # Holliday's code saves as list[tensor(n_routes, max_len)]
        if isinstance(routes_data, list):
            routes_data = routes_data[0]
        if isinstance(routes_data, torch.Tensor):
            routes_np = routes_data.numpy()
        else:
            routes_np = np.array(routes_data)
    except ImportError:
        with open(pkl_path, "rb") as f:
            routes_data = pickle.load(f)
        if isinstance(routes_data, list):
            routes_data = routes_data[0]
        routes_np = np.array(routes_data)

    idx_to_name = _load_node_mapping()
    routes = []
    for i in range(routes_np.shape[0]):
        valid = routes_np[i][routes_np[i] >= 0]
        route_names = [idx_to_name[int(idx)] for idx in valid]
        routes.append(route_names)
    return routes


class _HollidayBaseline:
    """Base class for EA/NEA baselines using pre-computed routes."""

    route_key = None

    def __init__(self, env, config, num_runs, base_seed):
        from baselines.utils import create_main_save_dir
        self.env = env
        self.config = config
        self.num_runs = num_runs
        self.base_seed = base_seed
        self.main_save_dir, self.eval_root_dir = create_main_save_dir(config)

        pkl_path = ROUTE_FILES[self.route_key]
        if not os.path.exists(pkl_path):
            raise FileNotFoundError(
                f"Route file not found: {pkl_path}\n"
                f"Run the {self.route_key.upper()} baseline first using the "
                f"holliday conda env. See baselines/neural_evolutionary/README.md"
            )
        self.routes = _load_routes(pkl_path)
        print(f"Loaded {len(self.routes)} {self.route_key.upper()} routes "
              f"from {os.path.basename(pkl_path)}")

    def run(self):
        from baselines.utils import execute_runs
        from rl.env_utils import write_results_summary
        results, aggregated = execute_runs(self, self.num_runs, self.base_seed)
        write_results_summary(aggregated, self.num_runs, self.eval_root_dir,
                              'eval_results_summary.json')
        return results, aggregated

    def construct_path(self, state):
        """Return pre-computed routes (no construction needed)."""
        return self.routes


class NeuralEvolutionary(_HollidayBaseline):
    """NEA baseline: Neural Evolutionary Algorithm (Holliday et al., 2024)."""
    route_key = "nea"


class EvolutionaryAlgorithm(_HollidayBaseline):
    """EA baseline: non-neural Evolutionary Algorithm (Holliday et al., 2024)."""
    route_key = "ea"
